the search page broke.. TypeError: auth(...).protect is not a function
src/middleware.ts (20:12) @ <unknown>

  18 | export default clerkMiddleware((auth, req) => {
  19 |   if (!isPublicRoute(req)) {
> 20 |     auth().protect();
     |            ^
  21 |   }
  22 | });
  23 |
Call Stack
10

Show 9 ignore-listed frame(s)
<unknown>
src/middleware.ts (20:12)